#!/bin/bash

echo "\nMETACORE"
cd ../MetaCore/src
dotnet build --configuration Debug

echo "\nMETAART"
cd ../../MetaArt/MetaArt
dotnet build --configuration Debug

echo "\nMETA3D"
cd ../Meta3D
dotnet build --configuration Debug

echo "\nMETABUTTON"
cd ../../MetaButton/src
dotnet build --configuration Debug

echo "\nMETAART_VIEWERS"
cd ../../MetaArt/MetaArt.Viewers
dotnet build --configuration Debug MetaArt.Xamarin.sln

cd ../../MetaArt