#!/bin/bash

echo "\nMETACORE"
cd ../MetaCore/src
dotnet restore
dotnet build --configuration Debug

echo "\nMETAART"
cd ../../MetaArt/MetaArt
dotnet restore
dotnet build --configuration Debug

echo "\nMETABUTTON"
cd ../../MetaButton/src
dotnet restore
dotnet build --configuration Debug

echo "\nMETAART_VIEWERS"
cd ../../MetaArt/MetaArt.Viewers
dotnet restore MetaArt.Xamarin.sln
dotnet build --configuration Debug MetaArt.Xamarin.sln

cd ../../MetaArt