#!/bin/bash
MSBuildExtensionsPath="/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/xbuild;/Library/Frameworks/Mono.framework/External/xbuild/;/Applications/Visual Studio (Preview).app/Contents/MonoBundle/AddIns/MonoDevelop.Docker/MSbuild"

echo "\nMETACORE"
cd ../MetaCore/src
dotnet clean -clp:ErrorsOnly --configuration Debug
dotnet clean -clp:ErrorsOnly --configuration Release

echo "\nMETAART"
cd ../../MetaArt/MetaArt
dotnet clean -clp:ErrorsOnly --configuration Debug
dotnet clean -clp:ErrorsOnly --configuration Release

echo "\nMETA3D"
cd ../Meta3D
dotnet clean -clp:ErrorsOnly --configuration Debug
dotnet clean -clp:ErrorsOnly --configuration Release

echo "\nMETABUTTON"
cd ../../MetaButton/src
dotnet clean -clp:ErrorsOnly --configuration Debug
dotnet clean -clp:ErrorsOnly --configuration Release

echo "\nMETAART_VIEWERS"
cd ../../MetaArt/MetaArt.Viewers
dotnet clean -clp:ErrorsOnly --configuration Debug MetaArt.Viewers.sln /p:EnableWindowsTargeting=true
dotnet clean -clp:ErrorsOnly --configuration Release MetaArt.Viewers.sln /p:EnableWindowsTargeting=true

cd ../../MetaArt

rm -rf ~/.nuget/packages/metacore
rm -rf ~/.nuget/packages/metaart
rm -rf ~/.nuget/packages/metaart.skia
rm -rf ~/.nuget/packages/metaart.xamarinforms