#!/bin/bash

echo "\nMETACORE"
cd ../MetaCore/src
dotnet clean --configuration Debug
dotnet clean --configuration Release

echo "\nMETAART"
cd ../../MetaArt/MetaArt
dotnet clean --configuration Debug
dotnet clean --configuration Release

echo "\nMETA3D"
cd ../Meta3D
dotnet clean --configuration Debug
dotnet clean --configuration Release

echo "\nMETABUTTON"
cd ../../MetaButton/src
dotnet clean --configuration Debug
dotnet clean --configuration Release

echo "\nMETAART_VIEWERS"
cd ../../MetaArt/MetaArt.Viewers
dotnet clean --configuration Debug MetaArt.Viewers.sln /p:EnableWindowsTargeting=true
dotnet clean --configuration Release MetaArt.Viewers.sln /p:EnableWindowsTargeting=true

cd ../../MetaArt

rm -rf ~/.nuget/packages/metacore
rm -rf ~/.nuget/packages/metaart
rm -rf ~/.nuget/packages/metaart.skia