#!/bin/bash
echo "\nmetaart\n"
git clean -fdx
rm -rf ~/.nuget/packages/metaart
rm -rf ~/.nuget/packages/metaart.skia

echo "\nmetacore\n"
cd ../metacore
git clean -fdx
rm -rf ~/.nuget/packages/metacore

echo "\nmetabutton\n"
cd ../metabutton
git clean -fdx
cd ../metaart